sudo: required
services:
  - docker

before_install:
  - docker build -t gubanx/docker-react -f Dockerfile.dev .

script:
  - docker run gubanx/docker-react npm run test -- --coverage

deploy:
  provider: heroku
  api_key:
    secure: '$HEROKU_KEY'
  app: guban-docker-react
  on:
    branch: master
